### ISSUE TITLE
Benefits/Difference over Streamlink?

### ISSUE THREAD

**Issue by unlocKing** [livecli/service.livecli.proxy#5]
Hey!

I see you are working with Leia, so that's a great advantage already :)

Just wondering what the main differences this fork will have over Streamlink?

Cheers!

**Comment by back-to** [comment]
basically it is a fork for custom stuff, 
- some custom plugins (universal m3u8 finder for every website)
- some custom commands
- able to run it on Android with Kodi

I will change back to streamlink again because of there new **Plugin Arguments API**,
as this allows me to use custom plugins with commands.

---

I will create a working solution for **streamlink** in the next couple days,
it's basically already done but needs some testing/cleanup

it will be somewhere here

https://github.com/back-to/liveproxy
https://github.com/back-to/service.liveproxy
https://github.com/back-to/repo

**Comment by unlocKing** [comment]
Sounds great..

Let me know if you need help with testing etc, will gladly assist!

I've just sent you a secure message on www.keybase.io - once you connect your github acc, you should see it, definitely worth your time :)

Cheers!

**Comment by unlocKing** [comment]
The first link to liveproxy is no longer working?

**Comment by back-to** [comment]
It's up again with a test version.
